# Generated by Django 4.1.1 on 2022-10-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategories',
        ),
    ]
