# Generated by Django 4.1.1 on 2022-10-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_rename_created_by_categories_auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='author',
        ),
    ]
