# Generated by Django 4.1.1 on 2022-10-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
