# Generated by Django 4.1.1 on 2022-10-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
